version: '3.8'

services:
  redis:
    image: redis:5.0
    ports:
      - '2710:6379'
    command: >
      sh -c "echo 'appendonly yes' >> /data/redis.conf &&
      echo 'appendfilename \"appendonly.aof\"' >> /data/redis.conf &&
      redis-server /data/redis.conf --requirepass REDIS_PASSWORD"
    volumes:
      - redis_data:/data
    restart: always
  api:
    build:
      context: .
    deploy:
      replicas: 2  # Start with 2 replicas, you can adjust this number
    ports:
      - '3001-3002:3002'
    depends_on:
      - redis
    restart: always

volumes:
  redis_data:
